# Generated by Django 6.0.5 on 2026-05-19 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Luxury Family Home', max_length=255)),
                ('price', models.IntegerField()),
                ('address', models.CharField(max_length=500)),
                ('beds', models.IntegerField()),
                ('baths', models.IntegerField()),
                ('sqft', models.IntegerField()),
                ('image', models.ImageField(upload_to='property_images/')),
                ('is_featured', models.BooleanField(default=False)),
                ('for_rent', models.BooleanField(default=True)),
            ],
        ),
    ]
