# Generated by Django 6.0.5 on 2026-05-21 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_propertylisting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertylisting',
            name='for_rent',
        ),
        migrations.RemoveField(
            model_name='propertylisting',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='propertylisting',
            name='sqft',
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='listing_type',
            field=models.CharField(choices=[('buy', 'Buy'), ('rent', 'Rent')], default='rent', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='propertylisting',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='propertylisting',
            name='image',
            field=models.ImageField(upload_to='properties/'),
        ),
        migrations.AlterField(
            model_name='propertylisting',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='propertylisting',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
