# Generated by Django 6.0.5 on 2026-05-21 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_remove_propertylisting_for_rent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertylisting',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='propertylisting',
            name='baths',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='propertylisting',
            name='beds',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='propertylisting',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='properties/'),
        ),
    ]
