# Generated by Django 6.0.5 on 2026-05-21 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_propertylisting_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertylisting',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='sqft',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
