# Generated by Django 6.0.5 on 2026-05-22 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_propertylisting_is_featured_propertylisting_sqft'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertylisting',
            name='property_type',
            field=models.CharField(default='House', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='status',
            field=models.CharField(default='status', max_length=100),
            preserve_default=False,
        ),
    ]
