# Generated by Django 6.0.5 on 2026-05-22 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_propertylisting_property_type_propertylisting_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertylisting',
            name='property_type',
            field=models.CharField(choices=[('villa', 'Villa'), ('apartment', 'Apartment'), ('house', 'House'), ('plot', 'Plot')], default='house', max_length=100),
        ),
        migrations.AlterField(
            model_name='propertylisting',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('sold', 'Sold'), ('pending', 'Pending')], default='available', max_length=100),
        ),
    ]
