# Generated by Django 6.0.5 on 2026-05-22 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_alter_propertylisting_property_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertylisting',
            name='baths',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propertylisting',
            name='beds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propertylisting',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('sold', 'Sold')], default='available', max_length=100),
        ),
    ]
