# Generated by Django 6.0.5 on 2026-06-03 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0010_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertylisting',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
