# Generated by Django 6.0.5 on 2026-06-04 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0012_visitrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitrequest',
            name='user',
        ),
    ]
