# Generated by Django 6.0.5 on 2026-06-05 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0013_remove_visitrequest_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertylisting',
            name='amenities',
            field=models.TextField(blank=True, help_text='Lift,Gym,Pool', null=True),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='furnishing',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='nearby_places',
            field=models.TextField(blank=True, help_text='School, Hospital, Mall', null=True),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='ownership',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='parking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='year_built',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visitrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
