# Generated by Django 6.0.5 on 2026-06-05 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    
    dependencies = [
        ('my_app', '0017_propertyoffer_status'),
    ]
    
    operations = [
        migrations.AlterField(
            model_name='propertylisting',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('sold', 'Sold'), ('rented', 'Rented')], default='available', max_length=100),
        ),
       
    ]
