# Generated by Django 6.0.5 on 2026-06-10 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0020_userprofile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertylisting',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
