# Generated by Django 6.0.5 on 2026-06-15 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0021_alter_propertylisting_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='propertylisting',
            name='amenities',
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='amenities',
            field=models.ManyToManyField(blank=True, related_name='properties', to='my_app.amenity'),
        ),
    ]
