# Generated by Django 6.0.5 on 2026-06-15 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0023_nearbyplace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertylisting',
            name='furnishing',
            field=models.CharField(blank=True, choices=[('unfurnished', 'Unfurnished'), ('semi_furnished', 'Semi Furnished'), ('fully_furnished', 'Fully Furnished')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='propertylisting',
            name='ownership',
            field=models.CharField(blank=True, choices=[('freehold', 'Freehold'), ('leasehold', 'Leasehold')], max_length=50, null=True),
        ),
    ]
