# Generated by Django 6.0.5 on 2026-06-16 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0024_alter_propertylisting_furnishing_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertylisting',
            name='parking',
        ),
    ]
