# Generated by Django 6.0.5 on 2026-06-22 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0025_remove_propertylisting_parking'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertylisting',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
