# Generated by Django 6.0.5 on 2026-06-23 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('my_app', '0026_propertylisting_approval_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='groups',
            field=models.ManyToManyField(blank=True, to='auth.group'),
        ),
        migrations.AddField(
            model_name='module',
            name='groups',
            field=models.ManyToManyField(blank=True, to='auth.group'),
        ),
        migrations.AlterField(
            model_name='propertylisting',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('Accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
