# Generated by Django 6.0.5 on 2026-06-23 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0027_child_groups_module_groups_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='child',
            old_name='groups',
            new_name='allowed_groups',
        ),
    ]
