# Generated by Django 6.0.5 on 2026-06-23 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0028_rename_groups_child_allowed_groups'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='groups',
            new_name='allowed_groups',
        ),
    ]
