# Generated by Django 6.0.5 on 2026-07-03 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0034_alter_blog_options_rename_image_blog_featured_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('General', 'General'), ('Buying Tips', 'Buying Tips'), ('Selling Tips', 'Selling Tips'), ('Investment', 'Investment'), ('Market Updates', 'Market Updates'), ('Home Loans', 'Home Loans'), ('Interior Design', 'Interior Design'), ('Company News', 'Company News')], default='General', max_length=100),
        ),
    ]
