# Generated by Django 6.0.5 on 2026-07-07 09:56

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0037_alter_blog_category'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='blog',
        #     name='category',
        #     field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blogs', to='my_app.blogcategory'),
        # ),
        migrations.AlterField(
            model_name='blog',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='featured_image'),
        ),
        migrations.AlterField(
            model_name='propertylisting',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='property_image'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='profile_image'),
        ),
    ]
